<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1992" started-at="2015-02-18T15:52:04Z" finished-at="2015-02-18T15:52:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1992" started-at="2015-02-18T15:52:04Z" finished-at="2015-02-18T15:52:06Z">
      <class name="com.maax.businessmanager.common.sampleTest">
        <test-method status="FAIL" signature="basicnavigation(java.util.Hashtable)[pri:0, instance:com.maax.businessmanager.common.sampleTest@49e4cb85]" name="basicnavigation" duration-ms="133" started-at="2015-02-18T11:52:05Z" data-provider="SuiteCommontestdata" finished-at="2015-02-18T11:52:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{qual period dp=Days, Browser=Chrome, Password=Welcome1, HC=Medavie Blue Cross, DepTermcalDP=Exact, Username=bcchase, Code=AUTO1B, Waitingperiod=0, Result=, Term.Age=60, TermDatecal=Exact, Runmode=Y, SubCate=Student, StartDatecal=Exact, DepTerm age=22, Status=Inforce, Category=Child, Qual Period=10, Description=Sample Test, BOB=Group, WaitingperiodDP=Days}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maax.businessmanager.util.TestBase.checkrunmodes(TestBase.java:72)
	at com.maax.businessmanager.common.sampleTest.basicnavigation(sampleTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicnavigation -->
        <test-method status="FAIL" signature="basicnavigation(java.util.Hashtable)[pri:0, instance:com.maax.businessmanager.common.sampleTest@49e4cb85]" name="basicnavigation" duration-ms="150" started-at="2015-02-18T11:52:06Z" data-provider="SuiteCommontestdata" finished-at="2015-02-18T11:52:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{qual period dp=Days, Browser=Chrome, Password=Welcome1, HC=Medavie Blue Cross, DepTermcalDP=Exact, Username=bcchase, Code=AUTO1C, Waitingperiod=0, Result=, Term.Age=60, TermDatecal=Exact, Runmode=Y, SubCate=Student, StartDatecal=Exact, DepTerm age=22, Status=Inforce, Category=Child, Qual Period=10, Description=Sample Test, BOB=Group, WaitingperiodDP=Days}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maax.businessmanager.util.TestBase.checkrunmodes(TestBase.java:72)
	at com.maax.businessmanager.common.sampleTest.basicnavigation(sampleTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicnavigation -->
        <test-method status="FAIL" signature="basicnavigation(java.util.Hashtable)[pri:0, instance:com.maax.businessmanager.common.sampleTest@49e4cb85]" name="basicnavigation" duration-ms="85" started-at="2015-02-18T11:52:06Z" data-provider="SuiteCommontestdata" finished-at="2015-02-18T11:52:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{qual period dp=Days, Browser=Chrome, Password=Welcome1, HC=Medavie Blue Cross, DepTermcalDP=Exact, Username=bcchase, Code=AUTO1B, Waitingperiod=0, Result=, Term.Age=60, TermDatecal=Exact, Runmode=Y, SubCate=Student, StartDatecal=Exact, DepTerm age=22, Status=Inforce, Category=Child, Qual Period=10, Description=Sample Test, BOB=Group, WaitingperiodDP=Days}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maax.businessmanager.util.TestBase.checkrunmodes(TestBase.java:72)
	at com.maax.businessmanager.common.sampleTest.basicnavigation(sampleTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicnavigation -->
        <test-method status="FAIL" signature="basicnavigation(java.util.Hashtable)[pri:0, instance:com.maax.businessmanager.common.sampleTest@49e4cb85]" name="basicnavigation" duration-ms="109" started-at="2015-02-18T11:52:06Z" data-provider="SuiteCommontestdata" finished-at="2015-02-18T11:52:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{qual period dp=Days, Browser=Chrome, Password=Welcome1, HC=Medavie Blue Cross, DepTermcalDP=Exact, Username=bcchase, Code=AUTO1C, Waitingperiod=0, Result=, Term.Age=60, TermDatecal=Exact, Runmode=Y, SubCate=Student, StartDatecal=Exact, DepTerm age=22, Status=Inforce, Category=Child, Qual Period=10, Description=Sample Test, BOB=Group, WaitingperiodDP=Days}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maax.businessmanager.util.TestBase.checkrunmodes(TestBase.java:72)
	at com.maax.businessmanager.common.sampleTest.basicnavigation(sampleTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicnavigation -->
        <test-method status="FAIL" signature="basicnavigation(java.util.Hashtable)[pri:0, instance:com.maax.businessmanager.common.sampleTest@49e4cb85]" name="basicnavigation" duration-ms="138" started-at="2015-02-18T11:52:06Z" data-provider="SuiteCommontestdata" finished-at="2015-02-18T11:52:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{qual period dp=Days, Browser=Firefox, Password=Welcome1, HC=Medavie Blue Cross, DepTermcalDP=Exact, Username=bcchase, Code=AUTO1B, Waitingperiod=0, Result=, Term.Age=60, TermDatecal=Exact, Runmode=Y, SubCate=Student, StartDatecal=Exact, DepTerm age=22, Status=Inforce, Category=Child, Qual Period=10, Description=Sample Test, BOB=Group, WaitingperiodDP=Days}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maax.businessmanager.util.TestBase.checkrunmodes(TestBase.java:72)
	at com.maax.businessmanager.common.sampleTest.basicnavigation(sampleTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicnavigation -->
        <test-method status="FAIL" signature="basicnavigation(java.util.Hashtable)[pri:0, instance:com.maax.businessmanager.common.sampleTest@49e4cb85]" name="basicnavigation" duration-ms="121" started-at="2015-02-18T11:52:06Z" data-provider="SuiteCommontestdata" finished-at="2015-02-18T11:52:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{qual period dp=Days, Browser=Firefox, Password=Welcome1, HC=Medavie Blue Cross, DepTermcalDP=Exact, Username=bcchase, Code=AUTO1C, Waitingperiod=0, Result=, Term.Age=60, TermDatecal=Exact, Runmode=Y, SubCate=Student, StartDatecal=Exact, DepTerm age=22, Status=Inforce, Category=Child, Qual Period=10, Description=Sample Test, BOB=Group, WaitingperiodDP=Days}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maax.businessmanager.util.TestBase.checkrunmodes(TestBase.java:72)
	at com.maax.businessmanager.common.sampleTest.basicnavigation(sampleTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicnavigation -->
      </class> <!-- com.maax.businessmanager.common.sampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
